# Modes: Lobby, Arena
Mode: Lobby
Messages:
  actionBar: 'Actualmente estas &cOCULTO'
  already: '&a&lINFO &8|&cYa estas con nickeado'
  removed: '&a&lINFO &8|&e Ya no estaras mas nickeado'
  nicked: "&a&lINFO &8|&e Has obtenido una nueva identidad"
# Game and Lobby modes requires mysql enabled
MySQL:
  enabled: false
  hostname: 127.0.0.1
  port: 3306
  database: Nicks
  username: root
  password: snake123
SkinIDs:
    - "2086519831"
    - "1565874944"
    - "91545730"
    - "1236815336"
SkinsNames:
- 'DanoMC'
- 'GabrielHD55'
- 'ElShared'
- 'GhostyCeh'
- 'C418'
- 'Earstorm'
- 'Hola'
- 'vexx21322'
- 'FoidzaFlow'
- 'Inzuki'
- 'Noggin'
- 'Anomaly'
- 'Whomobile'
- 'Glent'
- 'Nikmi'
- 'Gogo'
- 'Asrue2'
- 'swampie'
- 'torteela'
- 'muhammad'
- 'Dwragon'
- 'iam2little'
- 'Minecrafter'
- 'Conan3D'
- 'andersonmat'
- 'Swedman'
- 'CapnAwesom'
- 'elbowgrease12'
- 'Skype'
- 'Woodenwindows'
- 'SeanNanoware'
- 'Frog'
- '00Fraday00'
- 'Yumcake'
- 'Settler'
- 'ddrl46'
- '8zero'
- 'southworth'
- 'Micsi'
- 'A_Glitch'
- 'speedblader03'
- 'MightyMega'
- 'Seanm07'
- 'Chamonze'
- 'vista_df'
- 'Notsuru'
- 'sade1212'
- 'inacio'
- 'Snipex01'
- 'Foogles'
- 'Blocky_Lemon'
- 'Hackscore'
- 'Cool'
- 'PervertedHermit'
- 'Yunie'
- 'CherryJimbo'
- 'Fury'
- 'God'
- 'Romaji'
- 'chrisjon'
- 'Gravn'
- 'Spikespiegel'
- 'gagamel'
- 'ManningQB18'
- 'AndrewPH'
- 'Nether'
- 'Frewp'
- 'Explorer'
- 'SunriseMoon'
- 'Cheapshot'
- 'hug9000'
- 'Computrix'
- 'KingSam'
- 'Fish_warden'
- 'liv3d'
- 'Neath'
- 'Rixxz2'
- 'xHellfire'
- 'SolWolf'
- 'Razorlance'
- 'Dread'
- 'Israphel'
- 'Ryzo'
- 'Jakeobs'
- 'stolengoose'
- 'elrobto'
- 'TheJohan'
- 'subtraho'
- 'Creeper_Boss'
- 'Eisblut'
- 'mendo89'
- 'Graytico'
- 'Peter'
- 'jacksturrr416'
- 'phone'
- 'ControlFreak92'
- 'GRUML3N'
- '2easy4you'
- 'DoNotBeSad'
- 'zTqbii'
- 'TheSnowyWolf'
- 'IBimsAufsCrack'
- '1Dayi'
- 'iNatalia200_'